openapi: 3.0.3
info:
  title: WageAPI
  description: Wage Benchmarking Tool
  version: 1.0.0
servers:
  - url: 'https://wages.jobmarket.today/api'
components:
  securitySchemes:
    usernameHeader:
      type: apiKey
      in: header
      name: X-Username
paths:
  /:
    get:
      summary: Get salary estimate for a title in some location
      parameters:
        - name: title
          in: query
          description: blabla
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: blabla
          required: true
          schema:
            type: string
        - name: region
          in: query
          description:
          required: false
          schema:
            type: string
        - name: city
          in: query
          required: false
        - name: pay_period
          in: query
          required: false
        - name: showTopCompanies
          in: query
          required: false
        - name: showPercentiles
          in: query
          required: false
        - name: showJobUrl
          in: query
          required: false
